spring:
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  profiles:
    active: dev

  datasource:
    druid:
      master:
        #连接MySql
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/scone?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        #Druid连接配置
        initialSize: 20
        minIdle: 20
        maxActive: 30
        maxWait: 100000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select now()
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        keepAlive: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        resetEnable: true
        logAbandoned: true
        removeAbandoned: true
        removeAbandonedTimeout: 180000
      slave:
        #连接MySql
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/sctwo?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&serverTimezone=UTC
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
        #Druid连接配置
        initialSize: 20
        minIdle: 20
        maxActive: 30
        maxWait: 100000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select now()
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        keepAlive: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        resetEnable: true
        logAbandoned: true
        removeAbandoned: true
        removeAbandonedTimeout: 180000

server:
  port: 8080

mybatis:
  type-aliases-package: package com.sunchong.demo.model
  mapper-locations: classpath:mapper/**/*Mapper.xml

  configuration:
    map-underscore-to-camel-case: true


file:
  upload:
    path: D:\sunchong-demo\src\main\resources\upload\
